---
title: "PCV antibodies"
author: "Dan Weinberger"
date: "9/4/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(readxl)
library(reshape2)
```

```{r}
pcv7sts <- c('4','6B','9V','14','18C','19F','23F')
d1 <- read_excel("./Data/IgGGMCs2.xlsx")
names(d1)[1] <- 'vax'
d1$timepoint_dose_weeks <- NULL
d1.m <- melt(d1, id.vars=c('vax','Dose','Trial'))
d1.m$variable <- gsub('serotype', '', d1.m$variable)
d1.m <- d1.m[d1.m$variable %in% pcv7sts ,]
d1.c <- acast(d1.m, vax~Dose~Trial+variable)

boost <- as.data.frame(t(d1.c[,'Booster',]))
```

```{r}
plot(boost$PCV7, boost$PCV13, bty='l')
abline(a=0, b=1)
```

## From Voysey CID
Correlate of protection carriage
ST4: 1.16
ST6B 0.5
ST9V 1.31
ST14 2.48
ST19F 2.54
ST23F 0.63
```{r}
post.prim <- as.data.frame(t(d1.c[,'3rddoseP',]))
post.prim <- post.prim[!is.na(post.prim$PCV7) & !is.na(post.prim$PCV13),]

pre.boost <- as.data.frame(t(d1.c[,'preBooster',]))
pre.boost <- pre.boost[!is.na(pre.boost$PCV7) & !is.na(pre.boost$PCV13),]

```



#PCV7 13 ratio for post-primary, pre/post booster
```{r, fig.width=3, fig.height=8}
par(mfrow=c(3,1), mar=c(4,4,1,1))
all.ds <- list( 'post.prim'=post.prim,'pre.boost'=pre.boost, 'boost'=boost)
ds.labels= c('Post primary','Pre-Booster','Post-booster')

for(i in 1:length(all.ds)){
  ds <- all.ds[[i]]
ratio <- ds$PCV13/boost$PCV7
study <- gsub( "_.*$", "", rownames(ds) )
st <- gsub( ".*_", "", rownames(ds) )

plot.df <- cbind.data.frame(ratio, study, st)

plot(as.numeric(as.factor(plot.df$st)), plot.df$ratio, xaxt='n', bty='l', ylab='Ratio', main=ds.labels[i] , ylim=c(0,1.5))
axis (side=1, at=c(1:length(unique(plot.df$st))), labels=unique(plot.df$st) )
abline(h=1, lty=2)
}

```


```{r}
d1.m.boost <- d1.m[d1.m$Dose=='Booster',]
d1.c.alt <- dcast(d1.m.boost, vax~Trial+variable)

d1.c.alt$vax.d <- 0
d1.c.alt$vax.d[d1.c.alt$vax=='PCV13'] <- 1
d1.c.alt <- d1.c.alt[c(2,1),]

matplot(log(d1.c.alt[,-1]), type='l', col=rgb(0,0,0,alpha=0.1), lty=1)

```


